### PR TITLE
Disable path rewritting by default; allow WSRUN_* args; bump to 4.0.0

### PR DESCRIPTION
**Pull request by wh4everest**
TODO: couldn't run tests locally because of this:

```
  ● basic › should not break with namespaced pkgs

    Error

      Error: ENOENT: no such file or directory, open '/home/whoeverest/code/wsrun/tmp/wsrun-test-1/echo.out'

Test Suites: 1 failed, 1 passed, 2 total
Tests:       11 failed, 7 passed, 18 total
```

## What was the problem

Text that's identified as a relative path in the output is being incorrectly re-written, causing confusion while debugging application output. It was reported in #41

## Solution

* Disable path rewriting by default
* Users can now provide arguments via environment variables, like so: `WSRUN_NO_PREFIX=true` or `WSRUN_FAST_EXIT=false`
* Decouple prefixing setting and path rewritting, by introducing a new argument `--rewrite-paths` and the equivalent `WSRUN_REWRITE_PATHS=true`

Since this is a breaking change, I've bumped the version to 4.0.0

### CODE REVIEW

**Comment by spion** [comment]
I was wondering if we might want to bump wsrun to 4.0 and nip this in the bud early on making the non-prefixing default and controlling via env var for easier use.

eg in vscode you run 

`export WSRUN_PATH_SUBSTITUTION=1`

and from now on all commands in the terminal will pathsubstitute.

When existing users come and complain about the new behavior, we ask them to add this environment config to their vscode shell. but we shold check if this is easy to do?

**Comment by wh4everest** [comment]
How about adding an optional `wsrun: { .. }` section in the root package.json, instead of environment vars?

Regarding the "disabled by default" approach, I don't mind it. I didn't do that because it required a major bump in the version. But I don't oppose it in any way.

**Comment by spion** [comment]
package.json is again not exactly the right place, because do you want it to run in CI? If not, then tough luck the wsrun in CI also reads package.json

**Comment by wh4everest** [comment]
> package.json is again not exactly the right place, because do you want it to run in CI? If not, then tough luck the wsrun in CI also reads package.json

Got it.

Introducing `WSRUN_PATH_REWRITE` makes sense to me. We can later add other options with the same prefix -- perhaps allow specifying default arguments via the environment.

We'll need to mention them in the `--help` text.

**Comment by spion** [comment]
README/test?

**Pull request merged**
